getstoredxa: fix missing null termination in ts buffer
As reported at https://forums.gentoo.org/viewtopic-p-8294330.html ,
the ts[] buffer was not null-terminated, which means that sscanf
reads into uninitialized memory, and we could get garbage values
for the timestamp.

This could lead to false positives like:

  Error: corrupt file "/usr/share/zoneinfo/Africa/Libreville"

Fix the issue by initializing the whole array to zero.

Thanks to mike155 ( https://forums.gentoo.org/viewtopic-p-8294330.html#8294330 )
for the analysis!